version: "3.9"

services:
  # Database service
  mysql_db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  # WordPress (image based on Apache) with PHP 8.1
  wordpress:
    depends_on:
      - mysql_db
    image: wordpress:php8.1
    restart: always
    ports:
      - "8000:80"
      - 443:443
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'QM_ENABLE_CAPS_PANEL', true );
        define('ENABLE_CACHE', false);
        define('WPCF7_AUTOP', false );
      NEXT_VAR: false

    volumes:
      [
        "./wp-content:/var/www/html/wp-content:delegated",
        "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini",
        "./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini"
      ]

volumes:
  mysql: {}
