version: "3.9"

services:
  #Database service
  mysql_db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - "8888:80"

  #Wordpress (image based on Apache)
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile  # Verweise auf das neue Dockerfile
    depends_on:
      - mysql_db
    restart: always
    ports:
      - "8000:80"
      - 443:443
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_DISPLAY: true
      WORDPRESS_DEBUG_LOG: true
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
        define('DB_HOST', 'localhost:3306');
      NEXT_VAR: false      

    volumes:
      [
        "./wp-content:/var/www/html/wp-content:delegated",
        "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini",
        "./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini"
      ]
       
volumes:
  mysql: {}
